name: Build ECR Image and Trivy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Run Unit Testing
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to ECR
      id: ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Image
      run:  docker built -t pythonapp:latest

    - name: Scan with Trivy
      uses: aquasecurity/trivy-action@master
      with: 
        image-ref: pythonapp:latest
        exit-code: 1
        severity: HIGH,CRITICAL

